### ISSUE TITLE
Attached jpeg (Content-Type: application/octet-stream) is handled as Attachment, not shown inline.

### ISSUE THREAD

**Issue by agutierrez25249** [deltachat/deltachat-android#1251]
![deltachat-2020-02-11-145546](https://user-images.githubusercontent.com/52469394/74274646-6b9c1d80-4ce0-11ea-8fb2-5ea4405c1b59.jpg)

 This is an example of images sent by another messenger, Delta always shows it as an attachment, when it should show it as an image.
![JPEG_20200210_225906_538800379](https://user-images.githubusercontent.com/52469394/74274661-722a9500-4ce0-11ea-81c5-9c1661c6da1f.jpg)

**Comment by gerryfrancis** [comment]
@agutierrez25249 What happens when just the image itself (without any text) is embedded in the message body?

**Comment by agutierrez25249** [comment]
Send the same image as an attachment, from a conventional mail (MUA) and delta read it correctly. It seems that it is not the image but the mail, which is read incorrectly by Delta.

**Comment by gerryfrancis** [comment]
@agutierrez25249 I have a similar problem with mails sent from another mail client: https://github.com/deltachat/deltachat-core-rust/issues/1122 The message body includes only one image, no further text applied. I would like to know if you can verify this, please. Thanks in advance.

**Comment by gerryfrancis** [comment]
@agutierrez25249 Looks like some messages with mixed content in the body are problematic.

**Comment by angelo-fuchs** [comment]
@agutierrez25249 could you send such an email to contact - at - sommerfuchs.info, ideally from the messenger that created it in the first place? That way I can investigate the email directly. Please include you github username and a reference to this issue.

**Comment by agutierrez25249** [comment]
@angelo-fuchs 
I don't understand where to send the message, but I can leave you a screenshot.

[test.eml.txt](https://github.com/deltachat/deltachat-android/files/4553946/test.eml.txt)

**Comment by angelo-fuchs** [comment]
@agutierrez25249 I downloaded your message and removed all personal information from it.
The following is the result:

[embedded image modif](https://github.com/deltachat/deltachat-android/files/4573884/embedded_image_modif.eml.txt)

**Comment by angelo-fuchs** [comment]
The image was sent as "Content-Type: application/octet-stream;" instead of "Content-Type: image/jpeg".
When I change this, it is handled as image.
I'm uncertain how we should handle this atm.

**Comment by r10s** [comment]
i think, this is fixed by https://github.com/deltachat/deltachat-core-rust/pull/1396

and yes, i also think, images should just be shown as image - but i think, this is actually the case.

in any case, there seems to be no actionable item left :)

**Comment by angelo-fuchs** [comment]
The problem is still present on current master. 

This email is not displayed correctly:
[embedded image modif](https://github.com/deltachat/deltachat-android/files/4573884/embedded_image_modif.eml.txt)

**Comment by angelo-fuchs** [comment]
Mail is displayed like this:
![image](https://user-images.githubusercontent.com/10619521/85571111-2f84ac00-b634-11ea-80e3-0c09a108ee25.png)

**Comment by agutierrez25249** [comment]
yes i just checked the problem still exists in v1.10.3

**Comment by gerryfrancis** [comment]
@agutierrez25249 Do you know which app (mailer) sent the respective message? Was it SIJU (as stated in the file provided by @angelo-fuchs above)?

**Comment by agutierrez25249** [comment]
@gerryfrancis 
if she's the one who does that 
https://siju.es/ 
(Sorry for the delay in responding)

**Comment by gerryfrancis** [comment]
@angelo-fuchs Do you agree it would be helpful to reach out to the developers of SIJU to solve this?

**Comment by adbenitez** [comment]
I don't think that is needed, if it is an issue in the deltachat side it should be fixed if it is an issue in the SIJU app they should fix it

**Comment by gerryfrancis** [comment]
> if it is an issue in the SIJU app they should fix it

@adbenitez ... which is what I believe, but the developers might not be aware...

**Comment by angelo-fuchs** [comment]
@gerryfrancis It won't hurt to tell them that its improper to do so, but we must decide for ourselves if we want to handles such images or not.

Especially considering that other mailers do display an image here, it looks (to the user) as a bug with deltachat. Regular Users will not have any "But its not our fault" when others do display the image.

**Comment by gerryfrancis** [comment]
@angelo-fuchs Thanks for sharing your thoughts and knowledge, I did not know that other mailers interpret such snippets as images, too.

**Comment by AndreazLattmann** [comment]
In the new one I don't get this bug.
Have you tried with version 1.10.5 of Delta Chat?

**Comment by angelo-fuchs** [comment]
@AndreazLattmann Just tried with the email attached above and it still does not work.

**Comment by RubenDavidPerezJimenez** [comment]
I believe this have been resolved

**Comment by gerryfrancis** [comment]
@RubenDavidPerezJimenez Thanks for the update!

@agutierrez25249 Could you please check the latest version 1.12.5 and report back whether the issue is solved or not for you? Thank you in advance!

**Comment by r10s** [comment]
closing this, we can open a new issue with more recent information if needed.
