### ISSUE TITLE
Image with size 720x1280 or less pixels not displayed in chat view

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#1915]
- Android version:
Android 10.

- Device:
Fairphone FP2 (Lineage OS 17.1 build QQ3A.200805.001 from 2021-04-30).

- Delta Chat version:
1.19.2 (latest nightly build).

- Expected behavior:
Images with a size of 720 x 1280 or less pixels should be displayed in messages.

- Actual behavior:
Images with a size of 720 x 1280 or less pixels are not displayed in messages. (The place where the image supposed to be is blank.)

- Steps to reproduce the problem:
-- Receive a message with an image of 720 x 1280 or less pixels size. (A PNG file should fail as described.)

- Screenshots:
![Screenshot_20210504-103522_Delta_Chat_2](https://user-images.githubusercontent.com/51095533/116980093-1c1b8600-acc6-11eb-8b73-8e555be1bb07.png)

- Logs:
N/A.

**Comment by gerryfrancis** [comment]
I just found out that images with a size of less than 720 x 1280 cause the issue, too. Description adjusted...

**Comment by link2xt** [comment]
The image for testing from @adbenitez 
![1](https://user-images.githubusercontent.com/18373967/117055363-bf4eb880-ad23-11eb-8fc1-a2a6bedc1753.png)

**Comment by Gh0stz0x** [comment]
@gerryfrancis The issue was fixed in APNG but on DC (1.34.12) no...

**Comment by gerryfrancis** [comment]
In regard to https://github.com/deltachat/deltachat-android/issues/1915 , we still have issues with images that are not displayed in chats, although there is new evidence: When that happens, such entries can be found in the log:

`04-06 11:19:40.948  2189  2189 W ThumbnailView: Not re-loading slide file:///data/user/0/chat.delta.beta/files/accounts/378b7cfa-a213-4ff9-8291-057dfd33def3/dc.db-blobs/image_2023-04-06_09-02-31.webp`
`04-06 11:19:40.972  2189  2189 W ThumbnailView: Not re-loading slide file:///data/user/0/chat.delta.beta/files/accounts/378b7cfa-a213-4ff9-8291-057dfd33def3/dc.db-blobs/image_2023-04-06_09-02-43.webp`

There seems to be a false interpretation, because although the images were loaded (delivered) into the chat, they should be loaded for displaying as well (unless they are still in RAM).

The funny thing is: When you scroll back to images that were sent/received earlier, but not displayed, all of sudden they appear in the chat.

**Comment by AndreaLattmann** [comment]
I agree with what Gerry said 😔
