### ISSUE TITLE
Sharing if the filename include a "~" ends in a corrupt filname

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#2306]
If a filename (tried with a photo) includes a "~" the file will renamed to "*.bin"

Device: Nokia 5.3
Android 11
Delta Chat 1.30.1 (current play store version)

Steps to reproduce:
1. take a photo (eg. photo.png)
2. rename this file to photo~1.png (on my phone this happens if I crop a photo with the standard crop tool of Android)
3. use the share button of the fine manager in Android
4. the file extension will changed from "*.png" to "*.bin"

**Comment by Hocuri** [comment]
Should be fixed in nightly and the next release.

**Comment by webratte** [comment]
I have just installed the current nightly.
For me it's not fixed yet.

**Comment by gerryfrancis** [comment]
I can confirm that the issue still exists in the latest nightly build (version 1.30.2).

**Comment by Hocuri** [comment]
It's on my to-do list but I'm still working on other things (esp. AEAP) (so this shouldn't keep other folks from fixing this before me :)

**Comment by Hocuri** [comment]
Sooo the problem seems to be that `MimeTypeMap.getFileExtensionFromUrl(uri.toString())` (an Android system function) just gives up if there are any special characters, even if they are valid characters. A comment in there even says:

```java
            // if the filename contains special characters, we don't
            // consider it valid for our matching purposes:
            if ([...] Pattern.matches("[a-zA-Z_0-9\\.\\-\\(\\)\\%]+", filename)) { ...
```
I'll do a PR.

**Comment by webratte** [comment]
I can confirm, it's fixed in the current nightly 👍🏻

Thank you for your fast work.
