### ISSUE TITLE
Crashes when sharing from Delta Chat to some apps

### ISSUE THREAD

**Issue by Hocuri** [deltachat/deltachat-android#3597]
@Simon-Laux's file manager (Material Files, from F-Droid) throws this error: 

System.err: java8.nio.file.FileSystemException: content://com.b44t.messenger.attachments/f6ad6d62.log/nixos-infect.log: ContentResolver.query() with content://com.b44t.messenger.attachments/f6ad6d62.log/nixos-infect.log returned null

The fix is probably to return something sensible from `query()` in `AttachmentsContentProvider.java`:

```java
    @Override
    public Cursor query(Uri arg0, String[] arg1, String arg2, String[] arg3,
                        String arg4) {
        return null;
    }
```

Signal has it implemented, so, we can use their code as instructions for how implement it, but we can't copy the code due to licensing problems.

**Comment by Simon-Laux** [comment]
no the issue was reported to me, I just forwarded it. - I personally haven't tried it.

**Comment by inexcode** [comment]
Issue originally reported by me, thanks for forwarding and opening it!

**Comment by gerryfrancis** [comment]
I cannot reproduce this issue in version 2.11, so I think this might have been solved already.

**Comment by Hocuri** [comment]
I can still reproduce it:
- Install Material Files
- Open Material Files and grant access to all files
- Open Delta Chat
- Long-tap on an attachment and click the "Share" icon
- Select Material Files
- Click the "Save" icon

FTR, this could be fixed both in Delta Chat and in Material Files; it's debatable whose "fault" this is.

**Comment by gerryfrancis** [comment]
> FTR, this could be fixed both in Delta Chat and in Material Files; it's debatable whose "fault" this is.

I can reproduce this crash with Material Files as described, but not with Fossify File Manager.
